version: '3.8'
services:
  payment-mongodb:
    image: mongo:7-jammy
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PAYMENT_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${PAYMENT_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${PAYMENT_MONGO_DB}
    volumes:
      - ./payment-mongodb-data:/data/db
    networks:
      - payment-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - payment-network

  kafka-service:
    image: confluentinc/cp-kafka:7.6.0
    restart: unless-stopped
    ports:
      - '9092:9092'
      - '9093:9093'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BOOTSTRAP_SERVERS},PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - payment-network
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - '8099:8080'
    depends_on:
      kafka-service:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    networks:
      - payment-network

  payment-service:
    build: .
    restart: always
    ports:
      - '8084:8084'
    depends_on:
      payment-mongodb:
        condition: service_healthy
      kafka-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PAYMENT_MONGODB_URI=mongodb://${PAYMENT_MONGO_USER}:${PAYMENT_MONGO_PASSWORD}@payment-mongodb:27017/${PAYMENT_MONGO_DB}?authSource=admin
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge