spring:
  application:
    name: payment-service
  mongodb:
    uri: ${PAYMENT_MONGODB_URI:mongodb://localhost:27017/payment_db}
  data:
    mongodb:
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

server:
  port: 8084

kafka:
  topics:
    payment-created: payment.created